import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Sobre',
  description: 'Generated by create next app',
}

export default function Home() {
  return <h1>Sobre</h1>
}
